services:
  live:
    build:
      context: .
      target: live
    restart: always
    ports:
      - 4010:4010
    environment:
      - LIVE_BACKEND_ADDRESS=0.0.0.0:4010
      - ORIGIN=http://localhost:4080
      - RUST_LOG=live=trace

  api:
    build:
      context: .
      target: api
    restart: always
    ports:
      - 4050:4050
    environment:
      - API_BACKEND_ADDRESS=0.0.0.0:4050
      - RUST_LOG=api=debug

  frontend:
    build:
      context: ./dash/
      args:
        - NEXT_PUBLIC_LIVE_SOCKET_URL=http://localhost:4010
        - NEXT_PUBLIC_API_URL=http://localhost:4050
    restart: always
    ports:
      - 4080:4080
    depends_on:
      - api
      - live
    environment:
      - NEXT_PUBLIC_LIVE_SOCKET_URL=http://localhost:4010
      - NEXT_PUBLIC_API_URL=http://localhost:4050
